name: custom_research
description: "Pesquisar personalizáveis"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_analytics: ^10.8.10
  firebase_core: ^2.27.1
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_modular: ^6.3.2
  google_fonts: ^6.2.0
  signals: ^4.5.1
  signals_flutter: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  icons_launcher: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  
icons_launcher:
  image_path: "assets/icons/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true
